apiVersion: v1
kind: Namespace
metadata:
  name: ops-team
---
apiVersion: v1
kind: Namespace
metadata:
  name: acme1-istio-test
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: acme2-istio-test
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: acme3-istio-test
  labels:
    istio-injection: enabled