apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: acme-gateway
  namespace: ops-team
spec:
  listeners:
  - port:
      number: 443
    http: {}
    tls:
      mode: SIMPLE
      secretName: acme-istio-test-tls-secret
    allowedRouteTables:
    - host: acme1management.btcloudentitypoc.net
  - port:
      number: 443
    http: {}
    tls:
      mode: SIMPLE
      secretName: acme-istio-test-tls-secret
    allowedRouteTables:
    - host: acme2management.btcloudentitypoc.net
  - port:
      number: 443
    http: {}
    tls:
      mode: SIMPLE
      secretName: acme-istio-test-tls-secret
    allowedRouteTables:
    - host: acme3management.btcloudentitypoc.net
  workloads:
  - selector:
      labels:
        istio: ingressgateway
